routes/admin.php
<?php

/**
 * Admin Routes
 */
Route::prefix('admin')
     ->namespace('Admin')
     ->name('admin.')
     ->middleware(['auth.admin', 'role.check', 'first.access'])
     ->group(function () {

         Route::namespace('Dashboard')->group(function () {
             Route::name('dashboard.index')->get('/', 'DashboardController@index');

             Route::prefix('financial')->name('financial.')->group(function () {
                 Route::name('index')->get('/', 'FinancialController@index');
                 Route::get('/income', 'FinancialController@income');
                 Route::get('/outcome', 'FinancialController@outcome');
                 Route::get('/active-students', 'FinancialController@activeStudents');
                 Route::get('/registrations', 'FinancialController@registrations');
                 Route::get('/billing-summary', 'FinancialController@billingSummary');
                 Route::get('/billing-per-payment-type', 'FinancialController@billingPerPaymentType');
                 Route::get('/students-by-status', 'FinancialController@studentsByStatus');
             });

             Route::prefix('academic')->name('academic.')->group(function () {
                 Route::name('index')->get('/', 'AcademicController@index');
                 Route::get('/students-per-sex', 'AcademicController@studentsPerSex');
                 Route::get('/students-per-age-categories', 'AcademicController@studentsPerAgeCategories');
                 Route::get('/students-per-bands', 'AcademicController@studentsPerBands');
             });
         });

         Route::namespace('TrainingCenter')->group(function () {
             Route::resource('students', 'StudentController', ['except' => 'show']);
             Route::resource('age-categories', 'AgeCategoryController', ['except' => 'show']);
             Route::resource('origins', 'OriginController', ['except' => 'show']);
             Route::resource('guardians', 'GuardianController', ['except' => 'show']);
             Route::resource('teachers', 'TeacherController', ['except' => 'show']);
             Route::resource('bands', 'BandController', ['except' => 'show']);
             Route::resource('modalities', 'ModalityController', ['except' => 'show']);

             Route::resource('classrooms', 'ClassroomController');

             Route::prefix('classrooms')->name('classrooms.')->group(function () {
                 Route::resource('{classroom}/frequencies', 'FrequencyController');
             });

             Route::name('students.')->prefix('students')->group(function () {
                 Route::resource('attachments', 'AttachmentController', ['only' => ['show', 'update']]);

                 Route::resource('{registration}/graduations', 'GraduationController', ['except' => 'show']);
                 Route::resource('{registration}/installments', 'InstallmentController', ['except' => 'show']);
                 Route::resource('{registration}/issues', 'IssueController', ['only' => 'index']);

                 Route::name('skip-check')->post('/skip-check/{registration}', 'StudentController@skipcheck');
                 Route::name('graduations.print')->get('{registration}/print/{graduation}', 'GraduationController@print');
             });
         });

         Route::namespace('Auth')->prefix('users')->group(function () {
             Route::resource('permissions', 'PermissionController', ['except' => 'show']);
             Route::resource('roles', 'RoleController', ['except' => 'show']);

             Route::name('users.sendEmail')->get('/resend-confirmation/{user}', 'UserController@sendEmail');
             Route::name('users.activate')->get('/activate/{user}', 'UserController@activate');
             Route::name('users.deactivate')->get('/deactivate/{user}', 'UserController@deactivate');
         });

         Route::namespace('Finances')->group(function () {
             Route::resource('balance-records', 'BalanceRecordController', ['except' => 'show']);
             Route::resource('monthly-charge', 'MonthlyChargeController', ['only' => 'store']);
         });

         Route::namespace('Juno')->prefix('juno')->group(function() {
             Route::resource('transfer', 'TransferController', ['only' => ['index', 'store']]);
             Route::resource('split', 'SplitReportController', ['only' => ['index']]);
             Route::resource('invoices', 'InvoiceController', ['only' => ['index', 'store']]);
         });

         Route::namespace('Reports')->group(function(){
             Route::prefix('qualifications')->name('qualifications.')->group(function() {
                 Route::name('index')->get('/', 'QualificationController@index');
                 Route::name('print')->get('/print', 'QualificationController@print');
             });

              Route::prefix('reports')->name('reports.')->group(function () {
                 Route::name('balance')->get('/balance', 'BalanceController@index');
                 Route::name('overdue')->get('/overdue', 'OverdueController@index');
                 Route::name('class-billing')->get('/class-billing', 'BillingPerClassController@index');
              });
         });

         Route::resource('persons', 'PersonController', ['only' => 'show']);
         Route::resource('messages', 'MessageController');
         Route::resource('users', 'Auth\UserController', ['except' => 'show']);
         Route::resource('audits', 'AuditController', ['only' => ['index', 'show']]);
         Route::resource('subsidiaries', 'SubsidiaryController', ['except' => 'show']);

         Route::prefix('subsidiaries')->name('subsidiaries.')->group(function(){
             Route::name('documents.index')->get('{id}/documents', 'DocumentController@index');
             Route::name('documents.store')->post('{id}/documents/store', 'DocumentController@store');
         });

         Route::prefix('settings')->name('settings.')->group(function (){
             Route::name('edit')->get('/edit', 'SettingController@edit');
             Route::name('update')->put('/update', 'SettingController@update');
         });

     });

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::middleware('guest.admin')->group(function () {

    //Auto login
    Route::name('autologin')->get('/autologin/{token}', '\Watson\Autologin\AutologinController@autologin');

    Route::namespace('Auth\Sessions')->group(function () {

        Route::get('/', 'SessionController@showLoginForm');
        Route::name('login')->get('/login', 'SessionController@showLoginForm');
        Route::name('auth.session.login')->get('/acessar', 'SessionController@showLoginForm');
        Route::name('auth.session.login')->post('/acessar', 'SessionController@login');

        // Reset Password
        Route::name('auth.password.forgot')->get('/esqueci-minha-senha', 'ForgotPasswordController@showLinkRequestForm');
        Route::name('auth.password.processForgot')->post('/esqueci-minha-senha', 'ForgotPasswordController@sendResetLinkEmail');
        Route::name('auth.password.reset')->get('/cadastrar-senha/{token}/{email}', 'ResetPasswordController@showResetForm');
        Route::name('auth.password.processReset')->post('/cadastrar-senha', 'ResetPasswordController@reset');

        // First access
        Route::name('auth.activation.create')->get('/primeiro-acesso/{activation}', 'ActivationController@showActivationForm');
        Route::name('auth.activation.processCreate')->post('/primeiro-acesso/{token}', 'ActivationController@store');
    });
});

// Logout
Route::middleware('auth.admin')->group(function() {
    Route::name('auth.session.logout')->get('/sair', 'Auth\Sessions\SessionController@logout');
    Route::name('core.notifications.destroy')->delete('/excluir/{notification}', 'Core\NotificationController@destroy');
    Route::name('core.notifications.read')->put('/{notification}', 'Core\NotificationController@update');
});

app/Http/Controllers/Admin/Finances/BalanceRecordController.php
<?php

namespace App\Http\Controllers\Admin\Finances;

use App\Core\Services\TrainingCenter\RegistrationService;
use App\Core\Filters\BalanceRecordFilter;
use App\Core\Models\Subsidiary;
use App\Http\Controllers\Admin\BaseController;
use App\Http\Requests\SaveBalanceRecord;
use App\Core\Models\Financial\BalanceRecord;
use App\Core\Services\Financial\InstallmentService;
use Artesaos\SEOTools\Traits\SEOTools as SEOToolsTrait;
use Exception;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\View\View;

class BalanceRecordController extends BaseController
{
    use SEOToolsTrait;

    protected $installmentService;
    protected $registrationService;

    public function __construct(
        InstallmentService $installmentService,
        RegistrationService $registrationService
    ) {
        $this->seo()->setTitle('Lançamentos');

        $this->middleware('permission:view_balance_records', ['only' => ['index']]);
        $this->middleware('permission:add_balance_records', ['only' => ['create', 'store']]);
        $this->middleware('permission:edit_balance_records', ['only' => ['edit', 'update']]);
        $this->middleware('permission:delete_balance_records', ['only' => ['destroy']]);

        $this->installmentService = $installmentService;
        $this->registrationService = $registrationService;
    }

    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     *
     * @param \App\Core\Filters\BalanceRecordFilter $filter
     *
     * @return View
     */
    public function index(Request $request, BalanceRecordFilter $filter)
    {
        $subsidiaries = Subsidiary::pluck('name', 'id');
        $records      = BalanceRecord::filter($filter)
                                     ->latest()
                                     ->paginate(20)
                                     ->appends($request->except('page'));

        return view('admin.balance-records.index', compact(
            'records', 'subsidiaries'
        ));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return View
     */
    public function create()
    {
        $subsidiaries = Subsidiary::pluck('name', 'id');

        return view('admin.balance-records.create', compact('subsidiaries'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param SaveBalanceRecord $request
     *
     * @return RedirectResponse
     *
     * @throws Exception
     */
    public function store(SaveBalanceRecord $request)
    {
        $data = $request->validated();

        if (empty($data['repeat_times'])) {
            BalanceRecord::create($data);
        } else {
            $this->installmentService->generate($request);
        }

        toast()->success('Registro criado com sucesso.', 'Sucesso');

        return redirect()->route('admin.balance-records.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param BalanceRecord $balanceRecord
     *
     * @return View
     */
    public function edit(BalanceRecord $balanceRecord)
    {
        $subsidiaries = Subsidiary::pluck('name', 'id');

        return view('admin.balance-records.edit', compact(
            'balanceRecord', 'subsidiaries'
        ));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param SaveBalanceRecord $request
     * @param BalanceRecord $balanceRecord
     *
     * @return RedirectResponse
     */
    public function update(SaveBalanceRecord $request, BalanceRecord $balanceRecord)
    {
        $data = $request->validated();

        $balanceRecord->fill($data)->save();

        if($balanceRecord->paid() && $balanceRecord->isInvoice()){
            $this->registrationService->checkForIssues($balanceRecord->chargeable);
        }

        toast()->success('Registro modificado com sucesso.', 'Sucesso');

        return redirect()->route('admin.balance-records.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Request $request
     * @param BalanceRecord $balanceRecord
     *
     * @return JsonResponse|RedirectResponse
     *
     * @throws Exception
     */
    public function destroy(Request $request, BalanceRecord $balanceRecord)
    {
        $balanceRecord->delete();

        $msg = 'Registro removido com sucesso.';

        if ($request->ajax()) {
            return response()->json(['message' => $msg], 200);
        }

        toast()->success($msg, 'Success');

        return redirect()->back();
    }
}

resources/views/admin/balance-records/create.blade.php
@extends('layouts.default')

@section('content')

    {!! Form::open(['method' => 'POST', 'novalidate', 'role' => 'form', 'class' => 'form', 'route' => 'admin.balance-records.store']) !!}
    <section class="section">
        <div class="section-header mb-4">
            <div class="section-header-back">
                <a href="{{ route('admin.balance-records.index') }}"
                   class="btn btn-icon"
                   title="Voltar">
                    <i class="fas fa-arrow-left"></i>
                </a>
            </div>
            <h1>Novo lançamento</h1>
            {!! Breadcrumbs::render('balance_records.create') !!}
        </div>

        <div class="clearfix"></div>

        <div class="section-body mt-4">
            <div class="row">
                @include('admin.balance-records._form')
            </div>
        </div>
    </section>
    {!! Form::close() !!}

@endsection

resources/views/admin/balance-records/edit.blade.php
@extends('layouts.default')

@section('content')

    {!! Form::model($balanceRecord, ['method' => 'PUT', 'novalidate', 'role' => 'form', 'class' => 'form', 'route' => ['admin.balance-records.update', 'id' => $balanceRecord->id]]) !!}
    <section class="section">
        <div class="section-header mb-4">
            <div class="section-header-back">
                <a href="{{ route('admin.balance-records.index') }}"
                   class="btn btn-icon"
                   title="Voltar">
                    <i class="fas fa-arrow-left"></i>
                </a>
            </div>
            <h1>Editar lançamento</h1>
            {!! Breadcrumbs::render('balance_records.edit', $balanceRecord) !!}
        </div>

        <div class="clearfix"></div>

        <div class="section-body mt-4">
            <div class="row">
                @include('admin.balance-records._form')
            </div>
        </div>
    </section>
    {!! Form::close() !!}

@endsection

resources/views/admin/balance-records/index.blade.php
@extends('layouts.default')

@section('content')

    <section class="section">
        <div class="section-header mb-3">
            <h1>Lançamentos</h1>
            @can('add_balance_records')
                <div class="section-header-button mr-2">
                    <a href="{{ route('admin.balance-records.create') }}"
                       class="btn btn-success btn-icon btn-lg"
                       title="Adicionar"><i class="fas fa-plus"></i>
                        Adicionar</a>
                </div>
            @endcan
            {!! Breadcrumbs::render('balance_records.index') !!}
        </div>
        <div class="row">
            <div class="col-12">
                <h6 class="mb-3">Filtros</h6>
                <div class="card mb-0">
                    <div class="card-body mb-0">
                        {!! Form::open(['class' => 'form', 'novalidate', 'route' => 'admin.balance-records.index', 'method' => 'GET']) !!}
                        <div class="row">
                            <div class="col-lg-2 col-md-4 col-sm-12 mb-0 form-group">
                                {!! Form::text('name', Request::get('name'), ['class' => 'form-control', 'placeholder' => 'Aluno']) !!}
                            </div>
                            <div class="col-lg-2 col-md-2 col-sm-12 mb-0 form-group">
                                {!! Form::select('situation', enumOptions('payment_situation'), Request::get('situation'), ['class' => 'form-control', 'title' => 'Situação']) !!}
                            </div>
                            <div class="col-lg-2 col-md-2 col-sm-12 mb-0 form-group">
                                {!! Form::select('type', enumOptions('balance_record'), Request::get('type'), ['class' => 'form-control', 'title' => 'Tipo']) !!}
                            </div>
                            <div class="col-lg-2 col-md-2 col-sm-12 mb-1 form-group">
                                {!! Form::text('competence', Request::get('competence'), ['class' => 'form-control js-mask-monthyear', 'placeholder' => 'Competência']) !!}
                            </div>
                            @can('view_subsidiaries')
                                <div class="col-lg-2 col-md-2 col-sm-12 mb-1 form-group">
                                    {!! Form::select('subsidiary_id', $subsidiaries, Request::get('subsidiary_id'), ['class' => 'form-control', 'title' => 'Unidade']) !!}
                                </div>
                            @endcan
                            <div class="col-lg-1 col-md-1 col-sm-12 mb-0 form-group ml-auto">
                                <a href="#"
                                   class="btn btn-icon btn-block btn-danger"
                                   title="Limpar Campos">
                                    <i class="fas fa-ban lg-icon"></i>
                                </a>
                            </div>
                            <div class="col-lg-1 col-md-1 col-sm-12 mb-0 form-group">
                                <button type="submit"
                                        class="btn btn-icon btn-block btn-success">
                                    <i class="fas fa-search lg-icon"></i>
                                </button>
                            </div>
                        </div>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
        <div class="section-body mt-4">
            <div class="row mt-4">
                <div class="col-lg-12 col-sm-12">
                    <h6 class="mb-3">Listagem de lançamentos cadastrados</h6>
                    <div class="card">
                        <div class="card-body -table mb-0">
                            <div class="table-responsive">
                                <table class="table table-striped overflow mb-0">
                                    <tbody>
                                        <tr class="tr-a">
                                            <th>Status</th>
                                            <th>Tipo</th>
                                            <th>Aluno</th>
                                            <th>Descrição</th>
                                            <th title="Valor cobrado - pago">Valor</th>
                                            <th title="Data de vencimento - pagamento">Data</th>
                                            <th>Ações</th>
                                        </tr>
                                        @forelse($records as $record)
                                            <tr class="tr-item td-border">
                                                <td class="td-item">
                                                    @if(empty($record->payment_date))
                                                        @if(today()->gt($record->due_date))
                                                            <i title="Atrasado"
                                                               class="fas fa-exclamation-triangle text-danger"></i>
                                                        @else
                                                            <i title="Pedente"
                                                               class="fas fa-question-circle text-warning"></i>
                                                        @endif
                                                    @else
                                                        <i title="Pago"
                                                           class="fas fa-check-circle text-success"></i>
                                                    @endif
                                                </td>
                                                <td class="td-item">{{ enumOptions('balance_record')[$record->type] }}</td>
                                                <td class="td-item">{{ $record->chargeable->student->user->name ?? '' }}</td>
                                                <td class="td-item">{{ $record->description }}</td>
                                                <td class="td-item">{{ money_parse_by_decimal($record->amount, 'BRL') }}
                                                    - {{ money_parse_by_decimal($record->amount_paid ?? '0.00', 'BRL') }}</td>
                                                <td class="td-item">{{ $record->due_date->format('d/m/Y') }} - {{ $record->payment_date ? $record->payment_date->format('d/m/Y') : '##/##/####' }}</td>
                                                <td class="td-item text-center text-muted">

                                                    <div class="dropdown">
                                                        <a href="#"
                                                           role="button"
                                                           id="dropdownMenuLink"
                                                           data-toggle="dropdown"
                                                           data-boundary="window"
                                                           title="Ações"
                                                           aria-haspopup="true"
                                                           aria-expanded="false">
                                                            <i class="fas fa-ellipsis-h"></i>
                                                        </a>

                                                        <div class="dropdown-menu"
                                                             aria-labelledby="dropdownMenuLink">

                                                            @can('edit_balance_records')
                                                                <a href="{{ route('admin.balance-records.edit', ['record' => $record->id]) }}"
                                                                   title="Editar"
                                                                   class="dropdown-item">
                                                                    <i class="icon far fa-edit lg"></i>
                                                                    Editar
                                                                </a>
                                                            @endcan

                                                            @can('delete_balance_records')
                                                                <a href="#"
                                                                   data-link="{{ route('admin.balance-records.destroy', ['record' => $record->id]) }}"
                                                                   data-title="{{ $record->description }}"
                                                                   title="Excluir"
                                                                   class="dropdown-item js-confirm-delete">
                                                                    <i class="icon far fa-trash-alt lg"></i>
                                                                    Excluir
                                                                </a>
                                                            @endcan
                                                        </div>
                                                    </div>
                                            </tr>
                                        @empty
                                            <tr class="tr-item td-border">
                                                <td colspan="8"
                                                    class="td-item text-center">
                                                    Nenhum registro encontrado
                                                </td>
                                            </tr>
                                        @endforelse
                                    </tbody>
                                    <tfoot>
                                        <tr class="tr-item td-border bg-white">
                                            <td class="td-item">
                                                <b>Total: {!! $records->total() !!}</b>
                                            </td>
                                            <td class="td-item"
                                                colspan="7">
                                                <div class="float-right">{!! $records->render() !!}</div>
                                            </td>
                                        </tr>
                                    </tfoot>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection